name: aemet-back
on:
  push:
    branches:
      - main

jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: aemet-back
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: aemet-back
        run: |
          docker build . --tag ghcr.io/deselikem/aemet-back:latest
          docker run ghcr.io/deselikem/aemet-back:latest
          docker push ghcr.io/deselikem/aemet-back:latest
